/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-06-28 04:36:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.easy.util.Conexion;
import java.util.Date;
import java.util.Calendar;
import java.io.*;
import java.util.*;
import java.net.*;
import java.sql.*;

public final class agregar_002dproductos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t   \t<meta charset='utf-8'>\r\n");
      out.write("   \t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("   \t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("   \t\t<script src=\"http://code.jquery.com/jquery-latest.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("   \t\t<script src=\"librerias/js/script.js\"></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" media=\"(max-width:3000px)\" href = \"librerias/css/menuCssResponsive.css\" type = \"text/css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href = \"librerias/css/tablas-reponsivas.css\" type = \"text/css\">\r\n");
      out.write("\t\t<link href=\"librerias/css/styleAgregar.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Agregar Producto</title>\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("<div class=\"\">\r\n");
      out.write("\t<a href=\"index.html\"><img width=\"25%\" src=\"librerias/img/easymart.png\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"cssmenu\">\r\n");
      out.write("<ul>\r\n");
      out.write("   <li><a href=\"welcome.jsp\">Inicio</a></li>\r\n");
      out.write("   <li class='has-sub'><a href =\"#\">Productos</a>\r\n");
      out.write("   \t\t<ul>\r\n");
      out.write("   \t\t\t <li><a href=\"agregar-productos.jsp\">Agregar Productos</a></li>\r\n");
      out.write("   \t\t\t <li><a href=\"eliminar-productos.jsp\">Eliminar Productos</a></li>\r\n");
      out.write("   \t\t\t <li><a href=\"modificar-productos.jsp\">Modificar Productos</a></li>\r\n");
      out.write("   \t\t</ul>\r\n");
      out.write("   </li>\r\n");
      out.write("      <li class='has-sub'><a href=\"#\">Trabajadores</a>\r\n");
      out.write("   \t\t <ul>\r\n");
      out.write("   \t\t\t <li><a href=\"agregar-empleado.jsp\">Agregar Empleado</a></li>\r\n");
      out.write("   \t\t\t <li><a href=\"eliminar-empleado.jsp\">Eliminar Empleado</a></li>\r\n");
      out.write("   \t\t\t <li><a href=\"modificar-empleado.jsp\">Modificar Empleado</a></li>\r\n");
      out.write("   \t\t</ul>\r\n");
      out.write("   </li>\r\n");
      out.write("   \t  <li class='has-sub'><a href=\"#\">Sucursales</a>\r\n");
      out.write("   \t  <ul>\r\n");
      out.write("   \t\t\t <li><a href=\"agregar-sucursal.jsp\">Agregar Sucursal</a></li>\r\n");
      out.write("   \t\t\t <li><a href=\"eliminar-sucursal.jsp\">Eliminar Sucursal</a></li>\r\n");
      out.write("   \t\t\t <li><a href=\"modificar-sucursal.jsp\">Modificar Sucursal</a></li>\r\n");
      out.write("   \t\t</ul>\r\n");
      out.write("   \t  </li>\r\n");
      out.write("   \t  <li><a href=\"pedidos.jsp\">Pedidos</a></li>\r\n");
      out.write("   <li><a class=\"logout\" href=\"index.jsp\" data-title=\"Log out\">Cerrar Sesion</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");

Conexion db = new Conexion();


out.println("<FORM id=contact-form ACTION=agregar-productos.jsp METHOD=post>");
out.println("Nombre Producto:<INPUT TYPE=TEXT NAME=NOMBRE pattern=[a-zA-Z]* required/><BR>");
out.println("Detalle:<INPUT TYPE=TEXT NAME=DETALLE pattern=[a-zA-Z]* required/><BR>");
out.println("Valor:<INPUT TYPE=NUMBER NAME=VALOR required/><BR>");

ResultSet ro = null;
Statement stam = db.Conectar().createStatement();
ro = stam.executeQuery("SELECT * FROM TIPO_PRODUCTO");

      out.write("\r\n");
      out.write("Tipo Producto :<TD data-th=\"Tipo Producto\">\r\n");
      out.write("<select NAME=\"ID_TIPOPRODUCTO\">\r\n");
      out.write("        ");
  while(ro.next()){ 
      out.write("\r\n");
      out.write("            <option value=");
      out.print(ro.getString(1) );
      out.write('>');
      out.print( ro.getString(2));
      out.write("</option>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("</TD><BR>\r\n");

ro.close();
stam.close();
out.println("Stock:<INPUT TYPE=NUMBER NAME=STOCK required/><BR>");



      out.write("\r\n");
      out.write("<input type=\"submit\" name=\"OK\" value=\"Agregar\" style=\"\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    width:100%;\r\n");
      out.write("    border:none;\r\n");
      out.write("    background: #272526;\r\n");
      out.write("    background-image:linear-gradient(bottom, #8C1C50 0%, #991D57 52%);\r\n");
      out.write("    background-image:-moz-linear-gradient(bottom, #8C1C50 0%, #991D57 52%);\r\n");
      out.write("    background-image: -webkit-linear-gradient(bottom, #686D6F 0%, #000000 52%);\r\n");
      out.write("    color:#FFF;\r\n");
      out.write("    margin:0 0 5px;\r\n");
      out.write("    padding:10px;\r\n");
      out.write("    border-radius:5px;\r\n");
      out.write("    top: 10px;\r\n");
      out.write("    position: inherit; onclick=validacion()\">\r\n");
      out.write("\r\n");

out.println("</form>");



if(request.getParameter("OK") != null)
{
	Connection canal = null;
	ResultSet tabla= null;
	Statement instruccion=null;

	Connection cn = db.Conectar();
	canal = cn;

	try {		
		instruccion = canal.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
		ResultSet.CONCUR_UPDATABLE);
	}catch(SQLException e) {};



	String nom = request.getParameter("NOMBRE");
	String det = request.getParameter("DETALLE");
	int vlr = Integer.parseInt(request.getParameter("VALOR"));
	int idtipo = Integer.parseInt(request.getParameter("ID_TIPOPRODUCTO"));
	int stock = Integer.parseInt(request.getParameter("STOCK"));

//construyendo select con condicion
String q="INSERT INTO PRODUCTO(NOMBRE, DETALLE, VALOR, ID_TIPOPRODUCTO, STOCK) VALUES ('"+nom+"','"+det+"',"+vlr+","+idtipo+","+stock+")";

try {
// agregando renglon (insert)
int n=instruccion.executeUpdate(q);
//avisando que se hizo la instruccion

      out.write("\r\n");
      out.write("<script>alert(\"REGISTRO INSERTADO\")</script>\r\n");


}
catch(SQLException e) {};
try {instruccion.close();canal.close();} catch(SQLException e) {};
}




      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t  function validarN(numero){\r\n");
      out.write("\t    if (!/^([0-9])*$/.test(numero))\r\n");
      out.write("\t      alert(\"El valor \" + numero + \" no es un número\");\r\n");
      out.write("\t  }\r\n");
      out.write("\t<script src=\"librerias/js/scripts.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
