/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-06-29 22:43:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import java.net.*;
import java.sql.*;
import com.easy.util.Conexion;

public final class pedidos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t   \t<meta charset='utf-8'>\r\n");
      out.write("   \t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("   \t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("   \t\t<script src=\"http://code.jquery.com/jquery-latest.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("   \t\t<script src=\"librerias/js/script.js\"></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" media=\"(max-width:3000px)\" href = \"librerias/css/menuCssResponsive.css\" type = \"text/css\">\r\n");
      out.write("<!--  MENU \t<link rel=\"stylesheet\" href = \"librerias/css/login.css\" type = \"text/css\"> -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href = \"librerias/css/tabla.css\" type = \"text/css\">\r\n");
      out.write("\t<!--  \t<link href=\"librerias/css/styleEliminar.css\" rel=\"stylesheet\">-->\r\n");
      out.write("\r\n");
      out.write("<title>Pedidos</title>\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("<div class=\"\">\r\n");
      out.write("\t<a href=\"index.html\"><img width=\"25%\" src=\"librerias/img/easymart.png\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"cssmenu\">\r\n");
      out.write("<ul>\r\n");
      out.write("   <li><a href=\"welcome.jsp\">Inicio</a></li>\r\n");
      out.write("   <li class='has-sub'><a href =\"#\">Productos</a>\r\n");
      out.write("   \t\t<ul>\r\n");
      out.write("   \t\t\t <li><a href=\"agregar-productos.jsp\">Agregar Productos</a></li>\r\n");
      out.write("   \t\t\t <li><a href=\"eliminar-productos.jsp\">Eliminar Productos</a></li>\r\n");
      out.write("   \t\t\t <li><a href=\"modificar-productos.jsp\">Modificar Productos</a></li>\r\n");
      out.write("   \t\t</ul>\r\n");
      out.write("   </li>\r\n");
      out.write("  <li class='has-sub'><a href=\"#\">Trabajadores</a>\r\n");
      out.write("   \t\t <ul>\r\n");
      out.write("   \t\t\t <li><a href=\"agregar-empleado.jsp\">Agregar Empleado</a></li>\r\n");
      out.write("   \t\t\t <li><a href=\"eliminar-empleado.jsp\">Eliminar Empleado</a></li>\r\n");
      out.write("   \t\t\t <li><a href=\"modificar-empleado.jsp\">Modificar Empleado</a></li>\r\n");
      out.write("   \t\t</ul>\r\n");
      out.write("   </li>\r\n");
      out.write("   <li class='has-sub'><a href=\"#\">Sucursales</a>\r\n");
      out.write("   \t  <ul>\r\n");
      out.write("   \t\t\t <li><a href=\"agregar-sucursal.jsp\">Agregar Sucursal</a></li>\r\n");
      out.write("   \t\t\t <li><a href=\"eliminar-sucursal.jsp\">Eliminar Sucursal</a></li>\r\n");
      out.write("   \t\t\t <li><a href=\"modificar-sucursal.jsp\">Modificar Sucursal</a></li>\r\n");
      out.write("   \t\t</ul>\r\n");
      out.write("   \t  </li>\r\n");
      out.write("   \t  <li><a href=\"pedidos.jsp\">Pedidos</a></li>\r\n");
      out.write("   <li><a class=\"logout\" href=\"index.jsp\" data-title=\"Log out\">Cerrar Sesion</a></li>\r\n");
      out.write("   \r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("function marcado(){\r\n");
      out.write("if (document.form.termin.checked) {\r\n");
      out.write("document.form.submit(); \r\n");
      out.write("     }\r\n");
      out.write("\t else{\r\n");
      out.write("\t alert(\"Debes aceptar los términos y condiciones\");\r\n");
      out.write("\t  document.form.termin.focus();\r\n");
      out.write("       return false; \r\n");
      out.write("\t }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");

// construyendo forma dinamica

out.println("<FORM id=contact-form ACTION=pedidos.jsp METHOD=post>");
out.println("Buscar pedidos");
out.println("<INPUT TYPE=SUBMIT NAME=TODOS VALUE=BUSCAR><BR>");
out.println("</FORM>");

Connection canal = null;
ResultSet tabla= null;
Statement instruccion=null;
Conexion db = new Conexion();
Connection cn = db.Conectar();
canal = cn;



if(request.getParameter("boleta")!=null && request.getParameter("pedido")!=null){
	
	Conexion con = new Conexion();
    Connection cnn = con.Conectar();
    String pedido = request.getParameter("pedido");
    String boleta = request.getParameter("boleta");
    String codigo = boleta + pedido;
 	String w = "UPDATE PEDIDO SET ID_TIPOESTADO = 4 WHERE ID_PEDIDO = "+pedido;
	try { 
		if(codigo!=null){
		Statement st = cnn.createStatement();
		st.executeUpdate(w);
		out.println("<center><img src=/EasyMart/qrservlet?qrtext="+codigo+" >");
		
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<h3>Codigo generado para la confirmacion del usuario</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<h3>Porfavor entregar a la persona para la lectura del codigo</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t");

		}
		else
		{
			
      out.write("\r\n");
      out.write("\t\t\t<div><h3>No se pudo generar el Pedido</h3>></div>\r\n");
      out.write("\t\t\t");
	
		}
	}catch(SQLException e) {};
		
	
    }
    


if(request.getParameter("cod") != null && request.getParameter("ped")!=null)
{
	try {
		instruccion = canal.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
		ResultSet.CONCUR_UPDATABLE);
		} catch(SQLException e) {};
	String codigo = request.getParameter("cod");
	String pedido = request.getParameter("ped");
	String z = "SELECT BP.ID_BOLETA,BP.ID_PRODUCTO,P.NOMBRE,SUM(BP.CANTIDAD) AS CANTIDAD FROM BOLETA_PRO BP JOIN PRODUCTO P ON P.ID_PRODUCTO = BP.ID_PRODUCTO WHERE BP.ID_BOLETA ="+codigo+" GROUP BY BP.ID_BOLETA,BP.ID_PRODUCTO,NOMBRE";
	try { tabla = instruccion.executeQuery(z);
		
	out.println("<form method=post action=pedidos.jsp?boleta="+codigo+"&pedido="+pedido+">");
	
	out.println("<center><TABLE class=rwd-table>");
	out.println("<tr><th>Codigo Producto</th><th>Nombre Producto</th><th>Cantidad</th></tr>");
	
		while(tabla.next()) {
			out.println("<th>"+tabla.getString(2)+"</th>");
			out.println("<th>"+tabla.getString(3)+"</th>");
			out.println("<th>"+tabla.getString(4)+"</th>");
			out.println("<th><input type=checkbox required></th>");
			out.println("<tr>");
				
		}; 
		out.println("</TABLE></center>");
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<center><INPUT TYPE=SUBMIT NAME=btnEntrega value=\"Entregar Productos\"></center></form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

	} 
	catch(SQLException e) {};
}

if(request.getParameter("TODOS") != null)
{
//abriendo canal o enlace en su propio try-catch
try {

instruccion = canal.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
ResultSet.CONCUR_UPDATABLE);
} catch(SQLException e) {};
//construyendo select con condicion
String q = "SELECT P.ID_PEDIDO,P.ID_BOLETA,TE.DESCRIPCION,P.RUT_USUARIO,P.FECHA_INGRESO "+
		"FROM PEDIDO P "+
		"JOIN TIPO_ESTADO TE ON TE.ID_TIPOESTADO = P.ID_TIPOESTADO "+
		"WHERE TE.ID_TIPOESTADO = 1 AND FECHA_ENTREGA IS NULL";

try { tabla = instruccion.executeQuery(q);
//mandando resultset a tabla html
	while(tabla.next()) {
		
		out.println("<center><TABLE class=rwd-table>");
		out.println("<tr><th>N° Pedido : "+tabla.getString(1)+"</th></tr>");
		out.println("<tr><th>N° Boleta : "+tabla.getString(2)+"</th></tr>");
		out.println("<tr><th>Estado : "+tabla.getString(3)+"</th></tr>");
		out.println("<tr><th>Rut Usuario : "+tabla.getString(4)+"</th></tr>");
		out.println("<tr><th>Fecha Ingreso : "+tabla.getString(5)+"</th></tr>");
		
		out.println("<tr><th><a href=pedidos.jsp?cod="+tabla.getString(2)+"&ped="+tabla.getString(1)+">");
		
      out.write("\r\n");
      out.write("\t\t<center><INPUT TYPE=SUBMIT NAME=btnEliminar VALUE=+></center></a>\r\n");
      out.write("\t\t</th></tr>\r\n");
      out.write("\t\t</TABLE></center>\r\n");
      out.write("\t\t");

		}; 
} 
catch(SQLException e) {};
try {
//	tabla.close();
	instruccion.close();
	canal.close();
	} catch(SQLException e) {};
};



      out.write("\r\n");
      out.write("\t<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"librerias/js/jquery.slicknav.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$('#menu').slicknav();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
