/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-06-28 03:25:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class usuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>QR Code in Java Servlet - viralpatel.net</title>\r\n");
      out.write("\t<TITLE>Clearable Textboxes in jQuery</TITLE>\r\n");
      out.write("<STYLE>\r\n");
      out.write("body, input{\r\n");
      out.write("\tfont-family: Calibri, Arial;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("\tcolor: #0254EB\r\n");
      out.write("}\r\n");
      out.write("a:visited {\r\n");
      out.write("\tcolor: #0254EB\r\n");
      out.write("}\r\n");
      out.write("#header h2 {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tbackground-color: #3275A8;\r\n");
      out.write("\tmargin:0px;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html, body, #container { height: 100%; }\r\n");
      out.write("body > #container { height: auto; min-height: 100%; }\r\n");
      out.write("\r\n");
      out.write("#footer {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tz-index: 10;\r\n");
      out.write("\theight: 3em;\r\n");
      out.write("\tmargin-top: -3em;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("#content { padding-bottom: 3em; padding: 10px;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("}\r\n");
      out.write(".style1 {\r\n");
      out.write("\tborder: 3px solid #ffaa00;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".style2 {\r\n");
      out.write("\tborder: 2px solid #aaff77;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</STYLE>\r\n");
      out.write("</HEAD>\r\n");
      out.write("\r\n");
      out.write("<BODY>\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("<H2>\r\n");
      out.write("\t<a href=\"http://viralpatel.net\"><img border=\"0px\" src=\"logo.gif\" align=\"left\"/></a>\r\n");
      out.write("\tCreate QR Code in Java Servlet\r\n");
      out.write("</H2>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"qrservlet\" method=\"get\">\r\n");
      out.write("\t\t<p>Enter Text to create QR Code</p>\r\n");
      out.write("\t\t<input type=\"text\" name=\"qrtext\" />\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Generate QR Code\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("<br/>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\tCopyright &copy; <a href=\"http://viralpatel.net\">viralpatel.net</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
